PYTHON = python3
TEST_PATH = test/

# The @ makes sure that the command itself isn't echoed in the terminal
help:
	@echo "---------------HELP-----------------"
	@echo "To setup the project type make setup"
	@echo "To test the project type make test"
	@echo "To run the project type make run"
	@echo "------------------------------------"

test:
	${PYTHON} ${TEST_PATH}/Tests.py
